CodeSystem: ICD11MMS
Id: ICD11MMS
Title: "International Classification of Diseases, 11th Revision Mortality and Morbidity Statistics (MMS)"
Description: "The International Classification of Diseases, 11th Revision Mortality and Morbidity Statistics (MMS) is one of the ICD11 linearizations. Information about the ICD Foundation Component and the ICD11 Linearizations can be found in the complete reference guide here: [https://icd.who.int/icd11refguide/en/index.html](https://icd.who.int/icd11refguide/en/index.html)

\"**The ICD11 Linearizations (Tabular lists)**

A linearization is a subset of the foundation component, that is:

1. fit for a particular purpose: reporting mortality, morbidity, primary care or other uses;

2. composed of entities that are Mutually Exclusive of each other;

3. each entity is given a single parent.

Linearization is similar to the classical print versions of ICD Tabular List (e.g. volume I of ICD-10 or other previous editions). The main linearization of ICD-11 is Mortality and Morbidity Statistics (MMS). Various linearizations could be built at different granularity, use case or other purposes such as for Primary Care, Clinical Care or Research. The linkage from the foundation component to a particular linearization will ensure consistent use of the ICD.\"

ICD-11 for Mortality and Morbidity (ICD-11 MMS) can be downloaded in either print or electronic (spreadsheet) format from the browser in the Info tab located [here](https://icd.who.int/browse11/l-m/en)

*本IG僅內嵌ICD-11 MMS中第26章「傳統醫學病證」章節之254筆證候代碼片段(fragment)，非完整ICD-11內容。WHO官方ICD-API之FHIR終端服務(https://id.who.int/fhir)需OAuth2驗證，離線建置無法連線查詢，故改採內嵌片段方式確保可離線驗證。*"
* ^url = "http://id.who.int/icd/release/11/mms"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2022-11-15T00:00:00-00:00"
* ^publisher = "The World Health Organization"
* ^contact.name = "The World Health Organization; 20, avenue Appia 1211 Geneva 27, Switzerland"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://icd.who.int/en"
* ^copyright = "The WHO grants a license for \"commercial and non-commercial use\" of ICD-11

CC BY-ND 3.0 IGO

Detailed information can be found here: [https://icd.who.int/en/docs/icd11-license.pdf](https://icd.who.int/en/docs/icd11-license.pdf)

Contact licensing@who.int to obtain further information."
* ^caseSensitive = true
* ^content = #fragment

* #SE70 "陽證"
* #SE71 "陰證"
* #SE72 "熱證"
* #SE73 "寒證"
* #SE74 "實證"
* #SE75 "虛證"
* #SE76 "表證"
* #SE77 "裏證"
* #SE78 "寒熱中間證"
* #SE79 "虛實中間證"
* #SE7A "寒熱錯雜證"
* #SE7Y "其他特指的八綱證"
* #SE7Z "未特指的八綱證"
* #SE80 "風淫證"
* #SE81 "寒淫證"
* #SE82 "濕淫證"
* #SE83 "燥淫證"
* #SE84 "火熱淫證"
* #SE85 "暑淫證"
* #SE86 "疫癘證"
* #SE8Y "其他特指的外感證"
* #SE8Z "未特指的外感證"
* #SE90 "氣虛證"
* #SE91 "氣滯證"
* #SE92 "氣逆證"
* #SE93 "氣陷證"
* #SE94 "氣脫證"
* #SE9Y "其他特指的氣證"
* #SE9Z "未特指的氣證"
* #SF00 "血虛證"
* #SF01 "血瘀證"
* #SF02 "血熱證"
* #SF03 "血寒證"
* #SF04 "血燥證"
* #SF0Y "其他特指的血證"
* #SF0Z "未特指的血證"
* #SF10 "津液虧虛證"
* #SF11 "水毒證"
* #SF12 "燥痰證"
* #SF13 "濕痰證"
* #SF14 "痰火擾心證"
* #SF15 "風痰證"
* #SF1Y "其他特指的津液證"
* #SF1Z "未特指的津液證"
* #SF20 "精虛證"
* #SF2Y "其他特指的精證"
* #SF2Z "未特指的精證"
* #SF4Y "其他特指的氣血津液證"
* #SF4Z "未特指的氣血津液證"
* #SF50 "肝陰虛證"
* #SF51 "肝陽虛證"
* #SF52 "肝陽上亢證"
* #SF53 "肝氣虛證"
* #SF54 "肝血虛證"
* #SF55 "肝鬱血瘀證"
* #SF56 "肝風內動證"
* #SF57 "肝氣鬱結證"
* #SF58 "肝火上炎證"
* #SF59 "肝熱動風證"
* #SF5A "肝膽濕熱證"
* #SF5B "肝經濕熱證"
* #SF5C "寒滯肝脈證"
* #SF5D "膽氣虛證"
* #SF5E "膽鬱痰擾證"
* #SF5F "膽熱證"
* #SF5G "膽寒證"
* #SF5H "肝腎陰虛證"
* #SF5J "肝脾不和證"
* #SF5K "肝胃不和證"
* #SF5L "肝火犯胃證"
* #SF5M "肝火犯肺證"
* #SF5Y "其他特指的肝系證類"
* #SF5Z "未特指的肝系證類"
* #SF60 "心氣虛證"
* #SF61 "心血虛證"
* #SF62 "心氣血兩虛證"
* #SF63 "心脈痹阻證"
* #SF64 "心陰虛證"
* #SF65 "心氣陰兩虛證"
* #SF66 "心陽虛證"
* #SF67 "心陽暴脫證"
* #SF68 "心火上炎證"
* #SF69 "熱擾心神證"
* #SF6A "水氣凌心證"
* #SF6B "心神不寧證"
* #SF6C "憂傷神氣證"
* #SF6D "小腸氣滯證"
* #SF6E "小腸實熱證"
* #SF6F "小腸虛寒證"
* #SF6G "心肝血虛證"
* #SF6H "心膽氣虛證"
* #SF6J "心脾兩虛證"
* #SF6K "心肺氣虛證"
* #SF6L "心腎不交證"
* #SF6M "心腎陽虛證"
* #SF6Y "其他特指的心系證類"
* #SF6Z "未特指的心系證類"
* #SF70 "脾氣虛證"
* #SF71 "脾氣下陷證"
* #SF72 "脾虛氣滯證"
* #SF73 "脾虛食積證"
* #SF74 "脾不統血證"
* #SF75 "脾虛血虧證"
* #SF76 "脾陰虛證"
* #SF77 "脾陽虛證"
* #SF78 "濕熱蘊脾證"
* #SF79 "脾虛濕困證"
* #SF7A "脾虛水泛證"
* #SF7B "寒濕困脾證"
* #SF7C "胃氣虛證"
* #SF7D "胃氣上逆證"
* #SF7E "胃陰虛證"
* #SF7F "胃熱證"
* #SF7G "濕阻腸道證"
* #SF7H "寒邪犯胃證"
* #SF7J "寒滯腸道證"
* #SF7K "思傷脾氣證"
* #SF7L "肺脾兩虛證"
* #SF7M "脾腎陽虛證"
* #SF7Y "其他特指的脾系證類"
* #SF7Z "未特指的脾系證類"
* #SF80 "肺氣虛證"
* #SF81 "肺陰虛證"
* #SF82 "肺腎陰虛證"
* #SF83 "肺氣陰兩虛證"
* #SF84 "肺陽虛證"
* #SF85 "寒痰阻肺證"
* #SF86 "痰濁阻肺證"
* #SF87 "表寒肺熱證"
* #SF88 "肺熱熾盛證"
* #SF89 "痰熱壅肺證"
* #SF8A "風熱犯肺證"
* #SF8B "肺熱移腸證"
* #SF8C "風寒束肺證"
* #SF8D "燥邪犯肺證"
* #SF8E "肺燥腸閉證"
* #SF8F "大腸實熱證"
* #SF8G "大腸濕熱證"
* #SF8H "大腸津虧證"
* #SF8J "大腸虛寒證"
* #SF8Y "其他特指的肺系證類"
* #SF8Z "未特指的肺系證類"
* #SF90 "腎氣虛證"
* #SF91 "腎不納氣證"
* #SF92 "腎氣虛水泛證"
* #SF93 "腎陰虛證"
* #SF94 "腎陰陽兩虛證"
* #SF95 "腎虛髓虧證"
* #SF96 "腎精虧虛證"
* #SF97 "腎陽虛證"
* #SF98 "驚恐傷腎證"
* #SF99 "胞宮血熱證"
* #SF9A "痰凝胞宮證"
* #SF9B "胞宮濕熱證"
* #SF9C "寒凝胞宮證"
* #SF9D "胞宮虛寒證"
* #SF9E "膀胱蓄血證"
* #SF9F "膀胱蘊熱證"
* #SF9G "膀胱濕熱證"
* #SF9H "膀胱蓄水證"
* #SF9J "膀胱虛寒證"
* #SF9Y "其他特指的腎系證類"
* #SF9Z "未特指的腎系證類"
* #SG1Y "其他特指的臟腑證"
* #SG1Z "未特指的臟腑證"
* #SG20 "手太陰肺經證"
* #SG21 "手陽明大腸經證"
* #SG22 "足陽明胃經證"
* #SG23 "足太陰脾經證"
* #SG24 "手少陰心經證"
* #SG25 "手太陽小腸經證"
* #SG26 "足太陽膀胱經證"
* #SG27 "足少陰腎經證"
* #SG28 "手厥陰心包經證"
* #SG29 "手少陽三焦經證"
* #SG2A "足少陽膽經證"
* #SG2B "足厥陰肝經證"
* #SG2Y "其他特指的十二正經證"
* #SG2Z "未特指的十二正經證"
* #SG30 "督脈病證"
* #SG31 "任脈病證"
* #SG32 "陰蹻脈病證"
* #SG33 "陽蹻脈病證"
* #SG34 "陰維脈病證"
* #SG35 "陽維脈病證"
* #SG36 "衝脈病證"
* #SG37 "帶脈病證"
* #SG3Y "其他特指的奇經八脈證"
* #SG3Z "未特指的奇經八脈證"
* #SG5Y "其他特指的經絡證"
* #SG5Z "未特指的經絡證"
* #SG60 "太陽病證"
* #SG61 "陽明病證"
* #SG62 "少陽病證"
* #SG63 "太陰病證"
* #SG64 "少陰病證"
* #SG65 "厥陰病證"
* #SG6Y "其他特指的六經證"
* #SG6Z "未特指的六經證"
* #SG70 "上焦證"
* #SG71 "中焦證"
* #SG72 "下焦證"
* #SG7Y "其他特指的三焦證"
* #SG7Z "未特指的三焦證"
* #SG80 "濕遏衛陽證"
* #SG81 "溫邪侵襲肺衛證"
* #SG8Y "其他特指的衛分證"
* #SG8Z "未特指的衛分證"
* #SG90 "熱入氣分證"
* #SG91 "氣分濕熱證"
* #SG92 "濕阻氣分證"
* #SG9Y "其他特指的氣分證"
* #SG9Z "未特指的氣分證"
* #SH00 "營衛不和證"
* #SH01 "熱入營分證"
* #SH02 "熱入營血證"
* #SH0Y "其他特指的營分證"
* #SH0Z "未特指的營分證"
* #SH10 "血分證"
* #SH11 "熱入血分證"
* #SH1Y "其他特指的血分證"
* #SH1Z "未特指的血分證"
* #SH3Y "其他特指的衛氣營血證"
* #SH3Z "未特指的衛氣營血證"
* #SH40 "太陽人外感腰脊病證"
* #SH41 "太陽人內觸小腸病證"
* #SH42 "太陽人表裏兼病證"
* #SH4Y "其他特指的太陽人病證"
* #SH4Z "未特指的太陽人病證"
* #SH50 "少陽人少陽傷風證"
* #SH51 "少陽人亡陰證"
* #SH52 "少陽人胸膈熱證"
* #SH53 "少陽人陰虛證"
* #SH54 "少陽人表裏兼病證"
* #SH5Y "其他特指的少陽人病證"
* #SH5Z "未特指的少陽人病證"
* #SH60 "太陰人背顀表病證"
* #SH61 "太陰人胃脘寒證"
* #SH62 "太陰人肝熱證"
* #SH63 "太陰人燥熱證"
* #SH64 "太陰人表裏兼病證"
* #SH6Y "其他特指的太陰人病證"
* #SH6Z "未特指的太陰人病證"
* #SH70 "少陰人鬱狂證"
* #SH71 "少陰人亡陽證"
* #SH72 "少陰人太陰證"
* #SH73 "少陰人少陰證"
* #SH74 "少陰人表裏兼病證"
* #SH7Y "其他特指的少陰人病證"
* #SH7Z "未特指的少陰人病證"
* #SH9Y "其他特指的四象醫學病證"
* #SH9Z "未特指的四象醫學病證"
* #SJ1Y "其他特指的傳統醫學證候"
* #SJ1Z "未特指的傳統醫學證候"
