Logical: TraditionalChineseMedicineClinicRecordModel
Id: TraditionalChineseMedicineClinicRecordModel
Title: "中醫診所門診病摘(TraditionalChineseMedicineClinicRecord)之資料模型"
Description: "中醫診所門診病摘(TraditionalChineseMedicineClinicRecord)之資料模型"
* ^version = "0.1.0"
* documentInfo 1..1 BackboneElement "病歷文件資料"
  * hisdocPK 1..1 Identifier "HIS病歷唯一碼"
  * hospitalId 1..1 Identifier "醫事機構代碼"
  * hospitalName 1..1 string "醫事機構名稱"
  * sheetInfo 1..1 BackboneElement "病歷表單資料"
    * sheetId 1..1 Identifier "病歷表單編號"
    * sheetName 1..1 string "病歷表單名稱"
    * sheetVersion 1..1 id "病歷表單版本"
  * docInfo 1..1 BackboneElement "病歷文件資料"
    * docConfidentialityCode 1..1 code "文件敏感性"
    * createTime 1..1 dateTime "文件產生時間"
* patientInfo 1..1 BackboneElement "病人基本資料"
  * chatNo 1..1 Identifier "病歷號"
  * patientName 1..1 HumanName "病人姓名"
  * birthDate 0..1 date "出生日期"
  * visitIdentity 1..1 CodeableConcept "就醫身份"
  * gender 1..1 code "性別"
  * personalIDNumber 1..1 Identifier "身分證號"
  * contactInfo 0..1 BackboneElement "聯絡資訊"
    * homeTel 0..1 ContactPoint "住宅電話"
    * officeTel 0..1 ContactPoint "公司電話"
    * mobile 0..1 ContactPoint "行動電話"
  * bloodtype 0..1 	CodeableConcept "自述血型"
  * marriageStatus 0..1 CodeableConcept	 "婚姻"
  * occupation 0..1 CodeableConcept	"職業"
  * addressInfo 0..1 BackboneElement "病人相關住址"
    * originalAddressInfo 0..1 BackboneElement "病人戶籍地址資料"
      * originalAddressZipCode 0..1 code "病人戶籍地址郵遞區號"
      * originalAddresLocation 0..1 Address "病人戶籍地址"
    * contactAddressInfo 0..1 BackboneElement "病人聯絡地址資料"
      * contactAddressZipCode 0..1 code "病人聯絡地址郵遞區號"
      * contactAddressLocation 0..1 Address "病人聯絡地址"
  * email 0..1 ContactPoint "病人電子郵件地址"
  * history 0..1 CodeableConcept "過去病史"
  * allergy 0..1 string "過敏記錄"
  * emergencyContactInfo 0..* BackboneElement "緊急聯絡人相關資訊"
    * emName 0..1 HumanName "緊急聯絡人姓名"
    * emrelationshp 0..1 code "緊急聯絡人與病人關係"
    * emergencyContactWay 0..1 BackboneElement "緊急聯絡人聯絡方式"
      * emHomeTel 0..1 ContactPoint "緊急聯絡人住宅電話"
      * emOfficeTel 0..1 ContactPoint "緊急聯絡人公司電話"
      * emMobile 0..1 ContactPoint "緊急聯絡人行動電話"
  * childNumber 0..1 integer "病人子女數"
  * education 0..1 CodeableConcept "病人教育程度"
* encounter 1..1 BackboneElement "病人當次看診之相關資訊"
  * visitDate 1..1 dateTime "掛號(報到)日期時間"
  * visitSeq 1..1 Identifier "掛號序號"
  * department 1..1 CodeableConcept "看診科別"
  * doctorId 1..1 Identifier "看診醫師身分證號"
  * doctorName 1..1 HumanName "看診醫師姓名"
  * patientBloodPressure 0..1 BackboneElement "病人血壓"
    * systolicPressure 0..1 CodeableConcept "收縮壓"
    * diastoicPressure 0..1 CodeableConcept "舒張壓"
  * pulse 0..1 CodeableConcept "病人脈搏"
  * height 0..1 CodeableConcept "病人身高"
  * heightUnit 0..1 code "病人身高單位"
  * weight 0..1 CodeableConcept "病人體重"
  * weightUnit 0..1 code "病人體重單位"
  * bodytemperature 0..1 CodeableConcept "病人體溫"
  * chiefComplain 1..1 Annotation "病人主訴"
  * tongueCondition 0..1 string "病人舌象"
  * pulseCondition 0..1 string "病人脈象"
  * manifestation 0..1 string "病人證型"
  * therapeuticDiscipline 0..1 string "病人治則"
  * majorInjuryInfo 1..* BackboneElement "重大傷病相關資訊"
    * majorInjuryFlag 1..1 Annotation "重大傷病註記"
    * majorInjuryContent 0..* BackboneElement "重大傷病代碼與病名"
      * majorInjuryCode 1..1 code "重大傷病代碼"
      * majorInjuryName 1..1 string "重大傷病名稱"
  * diagnosisContent 1..* BackboneElement "診斷代碼與名稱"
    * diagcode 1..1 code "診斷代碼"
    * diagName 1..1 string "診斷名稱"
  * treatmenInfo 0..* BackboneElement "處置相關內容"
    * treatmentNHICCode 0..1 code "處置健保碼"
    * treatmentDescription 0..1 string "處置說明"
      * acupunctureInfo 0..* BackboneElement "針灸處置"
        * acupunctureRegionNHICode 1..* code "針灸部位"
        * acupuncturePointName 1..1 Annotation "針灸穴位"
        * acpuncturePointComment 0..1 string "針灸補充說明"
      * contusionInfo 0..* BackboneElement "傷科處置"
        * contusionRegionNHICode 1..1 code "傷科部位"
        * contusionTechnique 1..1 Annotation "傷科手法"
        * contusionComment 0..1 string "傷科補充說明"
      * dislocationInfo 0..* BackboneElement "脫臼整復處置"
        * dislocationRegionNHICode 1..1 code "脫臼整復部位"
        * dislocationTreatmentMethod 1..1 Annotation "脫臼整復處理方法"
        * dislocationComment 0..1 string "脫臼整復的補充說明"
  * doctorAdvise 0..1 Annotation "醫師囑咐"
* drugInfo 0..* BackboneElement "用藥紀錄相關內容"
  * drugNHICCode 0..1 code "藥品健保碼"
  * drugCode 1..1 code "藥品藥品碼"
  * drugName 1..1 string "藥品商品名"
  * dose 1..1 decimal "用量"
  * doseUnit 1..1 string "用量單位"
  * route 1..1 CodeableConcept "藥品服用方法"
  * frequency 1..1 CodeableConcept "藥品的使用頻率"
  * drugStartDate 1..1 date "用藥開始日期"
  * drugEndDate 1..1 date "用藥結束日期"
  * days 1..1 decimal "服藥天數"
  * totalAmount 1..1 decimal "藥品總劑量"
  * prescriptionMethod 0..1 CodeableConcept "藥品調劑方式"
  * packageNumber 0..1 integer "包數"
* examiationInfo 0..* BackboneElement "檢驗檢查相關內容"
  * examOrderDate 0..1 dateTime "檢驗檢查開單日期"
    * orderHospitalID 1..1 code "檢驗檢查開單醫事機構代碼"
    * orderHospitalName 1..1 string "檢驗檢查開單醫事機構名稱"
    * examHospitalID 1..1 code "檢驗檢查執行醫事機構代碼"
    * examHospitalName 1..1 string "檢驗檢查執行醫事機構名稱"
      * examDate 1..1 dateTime "檢查日期"
      * verifyDate 0..1 dateTime "報告日期"
      * testNHICode 0..1 code "健保檢驗檢查代碼"
      * testName 1..1 string "檢驗檢查名稱"
      * testResult 0..1 string "檢驗檢查結果值"
      * resultUnit 0..1 string "檢驗檢查結果單位"
      * resultFlag 0..1 CodeableConcept "檢驗檢查結果判斷註記"
      * resultComment 0..1 Annotation "檢驗檢查結果備註說明"
* imageInfo 0..* BackboneElement "圖檔報告內容"
  * imageFileName 1..1 Attachment "圖檔報告名稱"
  * imageContent 1..1 Attachment "圖檔報告內容"
* referenceInfo 0..* BackboneElement "參考附件資料內容"
  * referenceDocFileName 1..1 Attachment "附件檔名"
  * referenceDocContent 1..1 Attachment "附件內容"




Mapping: TraditionalChineseMedicineClinicRecord
Title: "TWCM"
Source: TraditionalChineseMedicineClinicRecordModel
Target: "https://www.nricm.edu.tw/twcm/"
* -> "BundleTWCM"

* documentInfo -> "(病歷文件資料)"
  * hisdocPK -> "BundleTWCM.identifier(HIS病歷唯一碼)"
  * hospitalId -> "entry:OrganizationTWCM.identifier(醫事機構代碼)"
  * hospitalName -> "entry:OrganizationTWCM.name(醫事機構名稱)"
  * sheetInfo -> "(病歷表單資料)"
    * sheetId -> "entry:CompositionTWCM.identifier(病歷表單編號)"
    * sheetVersion -> "entry:CompositionTWCM.meta.versionId(病歷表單版本)"
    * sheetName -> "entry:CompositionTWCM.title(病歷表單名稱)"
  * docInfo -> "(病歷文件資料)"
    * docConfidentialityCode -> "entry:CompositionTWCM.confidentiality.code(文件敏感性)"
    * createTime -> "entry:CompositionTWCM.date(文件產生時間)"

* patientInfo -> "(病人基本資料)"
  * chatNo -> "entry:PatientTWCM.identifier:medicalRecord(病歷號)"
  * patientName -> "entry:PatientTWCM.name(病人姓名)"
  * birthDate -> "entry:PatientTWCM.birthDate(出生日期)"
  * visitIdentity -> "entry:EncounterTWCM.extension.medicalIdentity.CodeableConcept(就醫身份)"
  * gender -> "entry:PatientTWCM.gender(性別)"
  * personalIDNumber -> "entry:PatientTWCM.identifier:idCardNumber(身分證號)"
  * contactInfo -> "(聯絡資訊)"
    * homeTel -> "entry:PatientTWCM.telecom.where(system='phone' and use='home').value(住宅電話)"
    * officeTel -> "entry:PatientTWCM.telecom.where(system='phone' and use='work').value(公司電話)"
    * mobile -> "entry:PatientTWCM.telecom.where(system='phone' and use='mobile').value(行動電話)"
  * bloodtype -> "entry:ObservationBloodtypeTWCM.where(code='882-1').valueCodeableConcept.text(自述血型)"
  * marriageStatus -> "entry:PatientTWCM.maritalStatus(婚姻)"
  * occupation -> "entry:ObservationOccupationTWCM.where(code='85658-3').valueCodeableConcept.text(職業)"
  * addressInfo -> "(病人相關住址)"
    * originalAddressInfo -> "(病人戶籍地址資料)"
      * originalAddressZipCode -> "entry:PatientTWCM.address.postalCode.valueCodeableConceptTW.coding:PostalCode3(病人戶籍地址郵遞區號)"
      * originalAddresLocation -> "entry:PatientTWCM.address.where(use='home').value(病人戶籍地址)"
    * contactAddressInfo -> "(病人聯絡地址資料)"
      * contactAddressZipCode -> "entry:PatientTWCM.address.postalCode.valueCodeableConceptTW.coding:PostalCode3(病人聯絡地址郵遞區號)"
      * contactAddressLocation -> "entry:PatientTWCM.address.where(use='billing').value(病人聯絡地址)"
  * email -> "entry:PatientTWCM.telecom.where(system ='email').value(病人電子郵件地址)"
  * history -> "entry:ConditionPastMedicalHistoryTWCM.CodeableConcept.text(過去病史)"
  * allergy -> "entry:AllergyIntoleranceTWCM.code.text(過敏記錄)"
  * emergencyContactInfo -> "(緊急聯絡人相關資訊)"
    * emName -> "entry:PatientTWCM.contact.name(緊急聯絡人姓名)"
    * emrelationshp -> "entry:PatientTWCM.contact.relationship(緊急聯絡人與病人關係)"
    * emergencyContactWay -> "(緊急聯絡人聯絡方式)"
      * emHomeTel -> "entry:PatientTWCM.contact.telecom.where(system='phone' and use='home').value(緊急聯絡人住宅電話)"
      * emOfficeTel -> "entry:PatientTWCM.contact.telecom.where(system='phone' and use='work').value(緊急聯絡人公司電話)"
      * emMobile -> "entry:PatientTWCM.contact.telecom.where(system='phone' and use='mobile').value(緊急聯絡人行動電話)"
  * childNumber -> "entry:PatientTWCM.extension.childnumber.valueInteger(病人子女數)"
  * education -> "entry:ObservationEducationLevelTWCM.where(code='80913-7').valueCodeableConcept.text(病人教育程度)"

* encounter -> "(病人當次看診之相關資訊)"
  * visitDate -> "entry:EncounterTWCM.period(掛號(報到)日期時間)"
  * visitSeq -> "entry:EncounterTWCM.identifier(掛號序號)"
  * department -> "entry:EncounterTWCM.servicetype(看診科別)"
  * doctorId -> "entry:PractitionerTWCM.identifier(看診醫師身分證號)"
  * doctorName -> "entry:PractitionerTWCM.name(看診醫師姓名)"
  * patientBloodPressure -> "(病人血壓)"
    * systolicPressure -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBloodPressureTWCM).where(code='8480-6').valueQuantity(收縮壓)"
    * diastoicPressure -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBloodPressureTWCM).where(code='8462-4').valueQuantity(舒張壓)"
  * pulse -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationHeartRateTWCM).where(code='8867-4').valueQuantity(病人脈搏)"
  * height -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBodyHeightTWCM).where(code='8302-2').valueQuantity(病人身高)"
  * heightUnit -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBodyHeightTWCM).where(code='8302-2').valueQuantity(病人身高單位)"
  * weight -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBodyWeightTWCM).where(code='29463-7').valueQuantity(病人體重)"
  * weightUnit -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBodyWeightTWCM).where(code='29463-7').valueQuantity(病人體重單位)"
  * bodytemperature -> "entry:ObservationVitalSignTWCM.hasMember.Reference(ObservationBodyTempTWCM).where(code='8310-5').valueQuantity(病人體溫)"
  * chiefComplain -> "entry:ConditionChiefComplaintTWCM.note(病人主訴)"
  * tongueCondition -> "entry:ObservationTongueConditionTWCM.where(code='249378009').valueString(病人舌象)"
  * pulseCondition -> "entry:ObservationPulseConditionTWCM.where(code='421608007').valueString(病人脈象)"
  * manifestation -> "entry:ObservationManifestationTWCM.where(code='38276004').valueString(病人證型)"
  * therapeuticDiscipline -> "entry:ObservationTherapeuticDisciplineTWCM.where(code='314705003').valueString(病人治則)"
  * majorInjuryInfo -> "(重大傷病相關資訊)"
    * majorInjuryFlag -> "entry:ObservationMajorIllnessTWCM.where(code='11338-1').valueBoolean(重大傷病註記)"
    * majorInjuryContent -> "(重大傷病代碼與病名)"
      * majorInjuryCode -> "entry:ConditionMajorIllnessTWCM.code(重大傷病代碼)"
      * majorInjuryName -> "entry:ConditionMajorIllnessTWCM.code.display(重大傷病代碼)"
  * diagnosisContent  -> "(診斷代碼與名稱)"
    * diagcode -> "entry:ConditionDiagnosisTWCM.code(診斷代碼)"
    * diagName -> "entry:ConditionDiagnosisTWCM.code.display(診斷名稱)"
  * treatmenInfo -> "(處置相關內容)"
    * treatmentNHICCode -> "entry:ProcedureTWCM.code(處置健保碼)"
    * treatmentDescription -> "entry:ProcedureTWCM.code.display(處置說明)"
      * acupunctureInfo -> "(針灸處置)"
        * acupunctureRegionNHICode -> "entry:ProcedureTWCM.bodySite.text(針灸部位)"
        * acupuncturePointName -> "entry:ProcedureTWCM.bodySite.extension.approach.valueString(針灸穴位)"
        * acpuncturePointComment -> "entry:ProcedureTWCM.note(針灸補充說明)"
      * contusionInfo -> "(傷科處置)"
        * contusionRegionNHICode -> "entry:ProcedureTWCM.bodySite.text(傷科部位)"
        * contusionTechnique -> "entry:ProcedureTWCM.bodySite.extension.approach.valueString(傷科手法)"
        * contusionComment -> "entry:ProcedureTWCM.note(傷科補充說明)"
      * dislocationInfo -> "(脫臼整復處置)"
        * dislocationRegionNHICode -> "entry:ProcedureTWCM.bodySite.text(脫臼整復部位)"
        * dislocationTreatmentMethod -> "entry:ProcedureTWCM.bodySite.extension.approach.valueString(脫臼整復處理方法)"
        * dislocationComment -> "entry:ProcedureTWCM.note(脫臼整復的補充說明)"
  * doctorAdvise -> "entry:CarePlanTWCM.note(醫師囑咐)"
* drugInfo -> "(用藥紀錄相關內容)"
  * drugNHICCode -> "entry:MedicationTWCM.code(藥品健保碼)"
  * drugCode -> "entry:MedicationTWCM.code(藥品藥品碼)"
  * drugName -> "entry:MedicationTWCM.code.display(藥品商品名)"
  * dose -> "entry:MedicationRequestTWCM.dosageInstruction.doseAndRate.doseQuantity.value(用量)"
  * doseUnit -> "entry:MedicationRequestTWCM.dosageInstructiondoseAndRate.doseQuantity.unit(用量單位)"
  * route -> "entry:MedicationRequestTWCM.dosageInstruction.route(藥品服用方法)"
  * frequency -> "entry:MedicationRequestTWCM.dosageInstruction.code(藥品的使用頻率)"
  * drugStartDate -> "entry:MedicationRequestTWCM.dosageInstruction.timing.repeat.boundsperiod.start(用藥開始日期)"
  * drugEndDate -> "entry:MedicationRequestTWCM.dosageInstruction.timing.repeat.boundsperiod.end(用藥結束日期)"
  * days -> "entry:MedicationRequestTWCM.dosageInstruction.timing.repeat.duration(服藥天數)"
  * totalAmount -> "entry:MedicationRequestTWCM.dosageInstruction.dispenseRequest.quantity(藥品總劑量)"
  * prescriptionMethod -> "entry:MedicationRequestTWCM.note(藥品調劑方式)"
  * packageNumber -> "entry:MedicationRequestTWCM.extension.packagenumber.valueInteger(包數)"

* examiationInfo -> "(檢驗檢查相關內容)"
  * examOrderDate -> "entry:ServiceRequestTWCM.occurrenceDateTime(檢驗檢查開單日期)"
    * orderHospitalID -> "entry:OrganizationTWCM.identifier(檢驗檢查開單醫事機構代碼)"
    * orderHospitalName -> "entry:OrganizationTWCM.name(檢驗檢查開單醫事機構名稱)"
    * examHospitalID -> "entry:OrganizationInspectionTWCM.identifier(檢驗檢查執行醫事機構代碼)"
    * examHospitalName -> "entry:OrganizationInspectionTWCM.name(檢驗檢查執行醫事機構名稱)"
      * examDate -> "entry:ObservationTWCM.effectiveDateTime(檢查日期)"
      * verifyDate -> "entry:DiagnosticReportTWCM.effectiveDateTime(報告日期)"
      * testNHICode -> "entry:ObservationTWCM.code(健保檢驗檢查代碼)"
      * testName -> "entry:ObservationTWCM.code.display(檢驗檢查名稱)"
      * testResult -> "entry:ObservationTWCM.valueQuantity.value(檢驗檢查結果值)"
      * resultUnit -> "entry:ObservationTWCM.valueQuantity.unit(檢驗檢查結果單位)"
      * resultFlag -> "entry:ObservationTWCM.interpretation(檢驗檢查結果判斷註記)"
      * resultComment -> "entry:ObservationTWCM.note(檢驗檢查結果備註說明)"
* imageInfo -> "(圖檔報告內容)"
  * imageFileName -> "entry:DocumentReferenceTWCM.content.attachment.title(圖檔報告名稱)"
  * imageContent -> "entry:DocumentReferenceTWCM.content.attachment.data(圖檔報告內容)"

* referenceInfo -> "(參考附件資料內容)"
  * referenceDocFileName -> "entry:DocumentReferenceTWCM.content.attachment.title(附件檔名)"
  * referenceDocContent -> "entry:DocumentReferenceTWCM.content.attachment.data(附件內容)"
