ValueSet: TWCMInspectionSpirit
Id: twcm-inspection-spirit
Title: "精神／意識／行為／情緒／性格(望神)值集"
Description: "中醫門診單精神／意識／行為／情緒／性格(望神)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"得神(有神)" "得神(有神)"
* TWCMClinicalFinding#"少神(神氣不足)" "少神(神氣不足)"
* TWCMClinicalFinding#"失神(無神)" "失神(無神)"
* TWCMClinicalFinding#"假神(殘燈復明；回光返照)" "假神(殘燈復明；回光返照)"
* TWCMClinicalFinding#"循衣摸床(捻衣摸床)" "循衣摸床(捻衣摸床)"
* TWCMClinicalFinding#"譫語" "譫語"
* TWCMClinicalFinding#"疲乏（神疲／情緒神疲）" "疲乏（神疲／情緒神疲）"
* TWCMClinicalFinding#"神疲" "神疲"
* TWCMClinicalFinding#"懶動" "懶動"
* TWCMClinicalFinding#"懶散" "懶散"
* TWCMClinicalFinding#"呆滯" "呆滯"
* TWCMClinicalFinding#"亢進" "亢進"
* TWCMClinicalFinding#"低落" "低落"
* TWCMClinicalFinding#"發狂(意識發狂)" "發狂(意識發狂)"
* TWCMClinicalFinding#"神昏" "神昏"
* TWCMClinicalFinding#"恍惚" "恍惚"
* TWCMClinicalFinding#"暈厥" "暈厥"
* TWCMClinicalFinding#"昏迷(意識昏迷)" "昏迷(意識昏迷)"
* TWCMClinicalFinding#"混亂" "混亂"
* TWCMClinicalFinding#"懶言(意識懶言)" "懶言(意識懶言)"
* TWCMClinicalFinding#"譫語(意識譫語)" "譫語(意識譫語)"
* TWCMClinicalFinding#"癡呆" "癡呆"
* TWCMClinicalFinding#"呵欠" "呵欠"
* TWCMClinicalFinding#"寡言" "寡言"
* TWCMClinicalFinding#"多言" "多言"
* TWCMClinicalFinding#"憤怒(情緒憤怒)" "憤怒(情緒憤怒)"
* TWCMClinicalFinding#"急躁" "急躁"
* TWCMClinicalFinding#"煩躁(情緒煩躁)" "煩躁(情緒煩躁)"
* TWCMClinicalFinding#"煩躁不安" "煩躁不安"
* TWCMClinicalFinding#"亢奮(情緒亢奮)" "亢奮(情緒亢奮)"
* TWCMClinicalFinding#"痛苦(情緒痛苦)" "痛苦(情緒痛苦)"
* TWCMClinicalFinding#"沈靜內向" "沈靜內向"
* TWCMClinicalFinding#"孤僻" "孤僻"

ValueSet: TWCMInspectionBody
Id: twcm-inspection-body
Title: "體(望)值集"
Description: "中醫門診單體(望)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"雞胸" "雞胸"
* TWCMClinicalFinding#"肋如串珠" "肋如串珠"
* TWCMClinicalFinding#"龜背" "龜背"
* TWCMClinicalFinding#"脊疳" "脊疳"
* TWCMClinicalFinding#"角弓反張" "角弓反張"
* TWCMClinicalFinding#"肢體痿廢" "肢體痿廢"
* TWCMClinicalFinding#"四肢拘急" "四肢拘急"
* TWCMClinicalFinding#"手足蠕動" "手足蠕動"
* TWCMClinicalFinding#"手足抽掣" "手足抽掣"
* TWCMClinicalFinding#"爪枯" "爪枯"
* TWCMClinicalFinding#"梭狀指" "梭狀指"
* TWCMClinicalFinding#"杵狀指" "杵狀指"
* TWCMClinicalFinding#"肌肉瞤動" "肌肉瞤動"
* TWCMClinicalFinding#"肌膚甲錯" "肌膚甲錯"
* TWCMClinicalFinding#"全身浮腫" "全身浮腫"
* TWCMClinicalFinding#"全身消瘦" "全身消瘦"
* TWCMClinicalFinding#"暈" "暈"
* TWCMClinicalFinding#"昏" "昏"
* TWCMClinicalFinding#"眩" "眩"
* TWCMClinicalFinding#"頭暈" "頭暈"
* TWCMClinicalFinding#"目眩" "目眩"
* TWCMClinicalFinding#"目暝" "目暝"

ValueSet: TWCMInspectionHeadFace
Id: twcm-inspection-headface
Title: "頭面部(望)值集"
Description: "中醫門診單頭面部(望)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"常色" "常色"
* TWCMClinicalFinding#"主色" "主色"
* TWCMClinicalFinding#"客色" "客色"
* TWCMClinicalFinding#"病色" "病色"
* TWCMClinicalFinding#"善色" "善色"
* TWCMClinicalFinding#"惡色" "惡色"
* TWCMClinicalFinding#"病色相克" "病色相克"
* TWCMClinicalFinding#"面青" "面青"
* TWCMClinicalFinding#"面赤" "面赤"
* TWCMClinicalFinding#"面黃" "面黃"
* TWCMClinicalFinding#"面白" "面白"
* TWCMClinicalFinding#"面黑" "面黑"
* TWCMClinicalFinding#"面色蒼白" "面色蒼白"
* TWCMClinicalFinding#"晄白" "晄白"
* TWCMClinicalFinding#"面焦" "面焦"
* TWCMClinicalFinding#"面色萎黃" "面色萎黃"
* TWCMClinicalFinding#"面黃胖" "面黃胖"
* TWCMClinicalFinding#"面色黧黑" "面色黧黑"
* TWCMClinicalFinding#"戴陽證" "戴陽證"
* TWCMClinicalFinding#"顴紅(顴赤)" "顴紅(顴赤)"
* TWCMClinicalFinding#"真臟色" "真臟色"
* TWCMClinicalFinding#"斑禿" "斑禿"
* TWCMClinicalFinding#"脂禿" "脂禿"
* TWCMClinicalFinding#"耳痔" "耳痔"
* TWCMClinicalFinding#"鼻痔" "鼻痔"
* TWCMClinicalFinding#"口唇紅腫(唇風)" "口唇紅腫(唇風)"
* TWCMClinicalFinding#"口唇青紫" "口唇青紫"
* TWCMClinicalFinding#"口唇淡白" "口唇淡白"
* TWCMClinicalFinding#"口唇焦裂(唇裂)" "口唇焦裂(唇裂)"
* TWCMClinicalFinding#"口舌糜爛" "口舌糜爛"
* TWCMClinicalFinding#"偽膜" "偽膜"
* TWCMClinicalFinding#"口瘡" "口瘡"
* TWCMClinicalFinding#"唇反" "唇反"
* TWCMClinicalFinding#"齒焦" "齒焦"
* TWCMClinicalFinding#"頭搖(搖頭)" "頭搖(搖頭)"
* TWCMClinicalFinding#"面青（面色青）" "面青（面色青）"
* TWCMClinicalFinding#"面色紅(面紅)" "面色紅(面紅)"
* TWCMClinicalFinding#"面白（面色白）" "面白（面色白）"
* TWCMClinicalFinding#"面紫（面色紫）" "面紫（面色紫）"
* TWCMClinicalFinding#"面黃（面色黃）黧黑" "面黃（面色黃）黧黑"
* TWCMClinicalFinding#"面暗（面色暗）" "面暗（面色暗）"
* TWCMClinicalFinding#"鬚髮早白" "鬚髮早白"
* TWCMClinicalFinding#"毛髮變異" "毛髮變異"
* TWCMClinicalFinding#"頭白禿" "頭白禿"
* TWCMClinicalFinding#"髮易脫落" "髮易脫落"
* TWCMClinicalFinding#"脫髮(鬚髮脫落)" "脫髮(鬚髮脫落)"
* TWCMClinicalFinding#"頭皮脫屑" "頭皮脫屑"
* TWCMClinicalFinding#"面浮腫" "面浮腫"
* TWCMClinicalFinding#"面腫脹" "面腫脹"
* TWCMClinicalFinding#"面乾" "面乾"
* TWCMClinicalFinding#"顏面抽搐(面抽搐)" "顏面抽搐(面抽搐)"
* TWCMClinicalFinding#"口角抽搐" "口角抽搐"
* TWCMClinicalFinding#"面苦笑" "面苦笑"
* TWCMClinicalFinding#"唇紫（唇色紫）" "唇紫（唇色紫）"
* TWCMClinicalFinding#"唇色白" "唇色白"
* TWCMClinicalFinding#"唇顫動(唇顫)" "唇顫動(唇顫)"
* TWCMClinicalFinding#"唇腫" "唇腫"
* TWCMClinicalFinding#"口唇濕爛(唇瘡)" "口唇濕爛(唇瘡)"
* TWCMClinicalFinding#"口唇潰瘍" "口唇潰瘍"
* TWCMClinicalFinding#"口頰潰爛" "口頰潰爛"
* TWCMClinicalFinding#"牙痛(牙齒痛)" "牙痛(牙齒痛)"
* TWCMClinicalFinding#"牙齒焦黑(牙齒乾、牙齒黑)" "牙齒焦黑(牙齒乾、牙齒黑)"
* TWCMClinicalFinding#"牙齒痿弱(牙齒酸)" "牙齒痿弱(牙齒酸)"
* TWCMClinicalFinding#"牙齦出血" "牙齦出血"
* TWCMClinicalFinding#"牙齦萎縮" "牙齦萎縮"
* TWCMClinicalFinding#"牙齦腐爛(牙齦瘡)" "牙齦腐爛(牙齦瘡)"
* TWCMClinicalFinding#"牙齒浮動" "牙齒浮動"
* TWCMClinicalFinding#"齲齒" "齲齒"
* TWCMClinicalFinding#"口中生瘡(口瘡)" "口中生瘡(口瘡)"
* TWCMClinicalFinding#"口噤" "口噤"
* TWCMClinicalFinding#"口閉" "口閉"
* TWCMClinicalFinding#"痛緩" "痛緩"
* TWCMClinicalFinding#"滑" "滑"
* TWCMClinicalFinding#"乾" "乾"
* TWCMClinicalFinding#"潤" "潤"
* TWCMClinicalFinding#"不乾" "不乾"
* TWCMClinicalFinding#"多唾" "多唾"
* TWCMClinicalFinding#"暗" "暗"
* TWCMClinicalFinding#"青色" "青色"
* TWCMClinicalFinding#"黑色" "黑色"
* TWCMClinicalFinding#"褐色" "褐色"
* TWCMClinicalFinding#"棕色" "棕色"
* TWCMClinicalFinding#"白色" "白色"
* TWCMClinicalFinding#"紫色" "紫色"
* TWCMClinicalFinding#"清色" "清色"
* TWCMClinicalFinding#"雜色" "雜色"
* TWCMClinicalFinding#"紅色" "紅色"
* TWCMClinicalFinding#"黃色" "黃色"
* TWCMClinicalFinding#"深紅色" "深紅色"
* TWCMClinicalFinding#"綠色" "綠色"
* TWCMClinicalFinding#"淡紅色" "淡紅色"

ValueSet: TWCMInspectionEye
Id: twcm-inspection-eye
Title: "目部(望)值集"
Description: "中醫門診單目部(望)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"口眼喎斜" "口眼喎斜"
* TWCMClinicalFinding#"戴眼反折" "戴眼反折"
* TWCMClinicalFinding#"瞪目直視" "瞪目直視"
* TWCMClinicalFinding#"目瞤" "目瞤"
* TWCMClinicalFinding#"睛凸" "睛凸"
* TWCMClinicalFinding#"瞼廢" "瞼廢"
* TWCMClinicalFinding#"睡時露睛(瞪睡露睛)" "睡時露睛(瞪睡露睛)"
* TWCMClinicalFinding#"口角歪斜" "口角歪斜"
* TWCMClinicalFinding#"口目歪斜" "口目歪斜"
* TWCMClinicalFinding#"不閉" "不閉"
* TWCMClinicalFinding#"目紅" "目紅"

ValueSet: TWCMInspectionSkin
Id: twcm-inspection-skin
Title: "皮膚(望)值集"
Description: "中醫門診單皮膚(望)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"陰斑" "陰斑"
* TWCMClinicalFinding#"陽斑" "陽斑"
* TWCMClinicalFinding#"疹" "疹"
* TWCMClinicalFinding#"白痱" "白痱"
* TWCMClinicalFinding#"熱氣瘡" "熱氣瘡"
* TWCMClinicalFinding#"濕疹" "濕疹"
* TWCMClinicalFinding#"紅(赤)" "紅(赤)"
* TWCMClinicalFinding#"紫" "紫"
* TWCMClinicalFinding#"瘀青" "瘀青"
* TWCMClinicalFinding#"紅斑" "紅斑"
* TWCMClinicalFinding#"垢" "垢"
* TWCMClinicalFinding#"血絲" "血絲"
* TWCMClinicalFinding#"黃疸" "黃疸"
* TWCMClinicalFinding#"白疕(乾癬、銀屑病、牛皮癬）" "白疕(乾癬、銀屑病、牛皮癬）"
* TWCMClinicalFinding#"皮膚疣" "皮膚疣"
* TWCMClinicalFinding#"痤瘡" "痤瘡"
* TWCMClinicalFinding#"潰瘍" "潰瘍"
* TWCMClinicalFinding#"痱子" "痱子"
* TWCMClinicalFinding#"疹(量：稠密／量多)" "疹(量：稠密／量多)"
* TWCMClinicalFinding#"腰部皰疹" "腰部皰疹"
* TWCMClinicalFinding#"掌部發疱" "掌部發疱"
* TWCMClinicalFinding#"癢(程度)" "癢(程度)"
* TWCMClinicalFinding#"疔瘡腫毒" "疔瘡腫毒"
* TWCMClinicalFinding#"光澤度(光亮、暗／無光澤暗淡)" "光澤度(光亮、暗／無光澤暗淡)"
* TWCMClinicalFinding#"按壓會凹陷不起" "按壓會凹陷不起"
* TWCMClinicalFinding#"散在性瘀斑" "散在性瘀斑"
* TWCMClinicalFinding#"或如蚊跡" "或如蚊跡"
* TWCMClinicalFinding#"或如蜈蚣" "或如蜈蚣"
* TWCMClinicalFinding#"凹陷" "凹陷"
* TWCMClinicalFinding#"長肉" "長肉"
* TWCMClinicalFinding#"斑" "斑"
* TWCMClinicalFinding#"紫斑" "紫斑"
* TWCMClinicalFinding#"瘡" "瘡"
* TWCMClinicalFinding#"瘀血" "瘀血"
* TWCMClinicalFinding#"瘀斑" "瘀斑"
* TWCMClinicalFinding#"紅疹" "紅疹"
* TWCMClinicalFinding#"白疹" "白疹"
* TWCMClinicalFinding#"乾（皮膚乾）" "乾（皮膚乾）"
* TWCMClinicalFinding#"乾燥" "乾燥"
* TWCMClinicalFinding#"潤" "潤"
* TWCMClinicalFinding#"不乾" "不乾"
* TWCMClinicalFinding#"硬（皮膚硬）" "硬（皮膚硬）"
* TWCMClinicalFinding#"指甲變形" "指甲變形"
* TWCMClinicalFinding#"指縫濕爛" "指縫濕爛"

ValueSet: TWCMListeningVoice
Id: twcm-listening-voice
Title: "語音(聞)值集"
Description: "中醫門診單語音(聞)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"金實不鳴" "金實不鳴"
* TWCMClinicalFinding#"金破不鳴" "金破不鳴"
* TWCMClinicalFinding#"聲怯" "聲怯"
* TWCMClinicalFinding#"聲嘶" "聲嘶"
* TWCMClinicalFinding#"譫語" "譫語"
* TWCMClinicalFinding#"鄭聲" "鄭聲"
* TWCMClinicalFinding#"錯語" "錯語"
* TWCMClinicalFinding#"獨語" "獨語"
* TWCMClinicalFinding#"狂言" "狂言"
* TWCMClinicalFinding#"語言謇澀" "語言謇澀"
* TWCMClinicalFinding#"譫妄" "譫妄"
* TWCMClinicalFinding#"短氣" "短氣"
* TWCMClinicalFinding#"少氣(氣微／呼吸微弱)" "少氣(氣微／呼吸微弱)"
* TWCMClinicalFinding#"太息(歎息)" "太息(歎息)"
* TWCMClinicalFinding#"氣促" "氣促"
* TWCMClinicalFinding#"咳嗽" "咳嗽"
* TWCMClinicalFinding#"難咳" "難咳"
* TWCMClinicalFinding#"乾咳" "乾咳"
* TWCMClinicalFinding#"呵欠" "呵欠"
* TWCMClinicalFinding#"腸鳴" "腸鳴"
* TWCMClinicalFinding#"聲音正常" "聲音正常"
* TWCMClinicalFinding#"沙啞(聲嘶)" "沙啞(聲嘶)"
* TWCMClinicalFinding#"聲低" "聲低"
* TWCMClinicalFinding#"聲高" "聲高"
* TWCMClinicalFinding#"有力" "有力"
* TWCMClinicalFinding#"無力" "無力"
* TWCMClinicalFinding#"小聲" "小聲"
* TWCMClinicalFinding#"大聲" "大聲"
* TWCMClinicalFinding#"無法發聲" "無法發聲"
* TWCMClinicalFinding#"亂七八糟的表達方式" "亂七八糟的表達方式"
* TWCMClinicalFinding#"喘" "喘"
* TWCMClinicalFinding#"氣喘" "氣喘"
* TWCMClinicalFinding#"呼吸急促" "呼吸急促"
* TWCMClinicalFinding#"呼吸微弱" "呼吸微弱"
* TWCMClinicalFinding#"呼吸聲大" "呼吸聲大"
* TWCMClinicalFinding#"氣逆" "氣逆"
* TWCMClinicalFinding#"喉中痰鳴" "喉中痰鳴"
* TWCMClinicalFinding#"呼吸痰鳴" "呼吸痰鳴"
* TWCMClinicalFinding#"痰鳴" "痰鳴"
* TWCMClinicalFinding#"喜太息(多嘆)" "喜太息(多嘆)"
* TWCMClinicalFinding#"咳" "咳"
* TWCMClinicalFinding#"咳鳴" "咳鳴"

ValueSet: TWCMSmellingOdor
Id: twcm-smelling-odor
Title: "氣味(聞)值集"
Description: "中醫門診單氣味(聞)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"口臭" "口臭"
* TWCMClinicalFinding#"噯腐" "噯腐"
* TWCMClinicalFinding#"噯氣" "噯氣"
* TWCMClinicalFinding#"無特殊" "無特殊"
* TWCMClinicalFinding#"體味" "體味"
* TWCMClinicalFinding#"其他" "其他"
* TWCMClinicalFinding#"臭味" "臭味"
* TWCMClinicalFinding#"腥味" "腥味"
* TWCMClinicalFinding#"不臭" "不臭"
* TWCMClinicalFinding#"異味" "異味"

ValueSet: TWCMInquiryColdHeat
Id: twcm-inquiry-coldheat
Title: "寒熱(問)值集"
Description: "中醫門診單寒熱(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"惡風" "惡風"
* TWCMClinicalFinding#"惡寒(恐寒)" "惡寒(恐寒)"
* TWCMClinicalFinding#"寒戰" "寒戰"
* TWCMClinicalFinding#"惡寒發熱" "惡寒發熱"
* TWCMClinicalFinding#"但寒不熱" "但寒不熱"
* TWCMClinicalFinding#"壯熱" "壯熱"
* TWCMClinicalFinding#"潮熱" "潮熱"
* TWCMClinicalFinding#"日晡潮熱(陽明潮熱)" "日晡潮熱(陽明潮熱)"
* TWCMClinicalFinding#"濕溫潮熱" "濕溫潮熱"
* TWCMClinicalFinding#"陰虛潮熱" "陰虛潮熱"
* TWCMClinicalFinding#"身熱夜甚" "身熱夜甚"
* TWCMClinicalFinding#"手足心熱" "手足心熱"
* TWCMClinicalFinding#"手足厥冷(冷肢)" "手足厥冷(冷肢)"
* TWCMClinicalFinding#"五心煩熱" "五心煩熱"
* TWCMClinicalFinding#"骨蒸" "骨蒸"
* TWCMClinicalFinding#"寒熱往來(往來寒熱)" "寒熱往來(往來寒熱)"
* TWCMClinicalFinding#"畏風" "畏風"
* TWCMClinicalFinding#"怕風" "怕風"
* TWCMClinicalFinding#"怕(惡、畏、陰)冷" "怕(惡、畏、陰)冷"
* TWCMClinicalFinding#"惡寒" "惡寒"
* TWCMClinicalFinding#"畏寒" "畏寒"
* TWCMClinicalFinding#"怕熱" "怕熱"
* TWCMClinicalFinding#"多天怕冷夏天怕熱" "多天怕冷夏天怕熱"
* TWCMClinicalFinding#"喜熱" "喜熱"
* TWCMClinicalFinding#"肢寒" "肢寒"
* TWCMClinicalFinding#"發熱" "發熱"
* TWCMClinicalFinding#"低熱" "低熱"
* TWCMClinicalFinding#"午後身熱" "午後身熱"
* TWCMClinicalFinding#"寒熱往來" "寒熱往來"
* TWCMClinicalFinding#"高溫" "高溫"
* TWCMClinicalFinding#"低溫" "低溫"
* TWCMClinicalFinding#"熱" "熱"
* TWCMClinicalFinding#"暖" "暖"
* TWCMClinicalFinding#"冷" "冷"
* TWCMClinicalFinding#"熱胸口熱" "熱胸口熱"
* TWCMClinicalFinding#"腰冷重(腰冷)" "腰冷重(腰冷)"
* TWCMClinicalFinding#"背冷" "背冷"
* TWCMClinicalFinding#"背熱" "背熱"
* TWCMClinicalFinding#"四肢冷" "四肢冷"
* TWCMClinicalFinding#"手心熱" "手心熱"
* TWCMClinicalFinding#"足心熱" "足心熱"

ValueSet: TWCMInquirySweat
Id: twcm-inquiry-sweat
Title: "汗(問)值集"
Description: "中醫門診單汗(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"無汗" "無汗"
* TWCMClinicalFinding#"自汗" "自汗"
* TWCMClinicalFinding#"戰汗" "戰汗"
* TWCMClinicalFinding#"冷汗" "冷汗"
* TWCMClinicalFinding#"熱汗" "熱汗"
* TWCMClinicalFinding#"頭汗" "頭汗"
* TWCMClinicalFinding#"手足心汗" "手足心汗"
* TWCMClinicalFinding#"脫汗(絕汗)" "脫汗(絕汗)"
* TWCMClinicalFinding#"心胸汗" "心胸汗"
* TWCMClinicalFinding#"陰汗" "陰汗"
* TWCMClinicalFinding#"不易流汗" "不易流汗"
* TWCMClinicalFinding#"絕汗" "絕汗"
* TWCMClinicalFinding#"少汗" "少汗"
* TWCMClinicalFinding#"多汗" "多汗"
* TWCMClinicalFinding#"盜汗" "盜汗"
* TWCMClinicalFinding#"心胸汗出" "心胸汗出"
* TWCMClinicalFinding#"手汗" "手汗"
* TWCMClinicalFinding#"足汗" "足汗"
* TWCMClinicalFinding#"腋汗" "腋汗"
* TWCMClinicalFinding#"汗出偏沮(右半身汗出／左半身汗出)" "汗出偏沮(右半身汗出／左半身汗出)"
* TWCMClinicalFinding#"黃汗" "黃汗"

ValueSet: TWCMInquiryBody
Id: twcm-inquiry-body
Title: "體(問)值集"
Description: "中醫門診單體(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"身痛" "身痛"
* TWCMClinicalFinding#"身重" "身重"
* TWCMClinicalFinding#"半身不遂" "半身不遂"
* TWCMClinicalFinding#"半身麻木" "半身麻木"
* TWCMClinicalFinding#"肌膚不仁" "肌膚不仁"
* TWCMClinicalFinding#"戰慄" "戰慄"
* TWCMClinicalFinding#"筋惕肉瞤" "筋惕肉瞤"
* TWCMClinicalFinding#"手足麻木" "手足麻木"
* TWCMClinicalFinding#"心痛徹背" "心痛徹背"
* TWCMClinicalFinding#"心下痛" "心下痛"
* TWCMClinicalFinding#"心煩" "心煩"
* TWCMClinicalFinding#"胸中熱" "胸中熱"
* TWCMClinicalFinding#"胸痞" "胸痞"
* TWCMClinicalFinding#"胸脅苦滿" "胸脅苦滿"
* TWCMClinicalFinding#"胸中煩熱" "胸中煩熱"
* TWCMClinicalFinding#"脅脹" "脅脹"
* TWCMClinicalFinding#"懸癖" "懸癖"
* TWCMClinicalFinding#"懊惱" "懊惱"
* TWCMClinicalFinding#"噯氣(聞問)" "噯氣(聞問)"
* TWCMClinicalFinding#"小腹痛" "小腹痛"
* TWCMClinicalFinding#"少腹痛" "少腹痛"
* TWCMClinicalFinding#"少腹拘急" "少腹拘急"
* TWCMClinicalFinding#"惡心" "惡心"
* TWCMClinicalFinding#"泛酸" "泛酸"
* TWCMClinicalFinding#"除中" "除中"
* TWCMClinicalFinding#"吐血" "吐血"
* TWCMClinicalFinding#"腰痠" "腰痠"
* TWCMClinicalFinding#"全身酸" "全身酸"
* TWCMClinicalFinding#"腰酸" "腰酸"
* TWCMClinicalFinding#"下肢酸(痠)" "下肢酸(痠)"
* TWCMClinicalFinding#"膝酸" "膝酸"
* TWCMClinicalFinding#"全身麻" "全身麻"
* TWCMClinicalFinding#"四肢麻木" "四肢麻木"
* TWCMClinicalFinding#"膝麻" "膝麻"
* TWCMClinicalFinding#"麻木" "麻木"
* TWCMClinicalFinding#"麻痺" "麻痺"
* TWCMClinicalFinding#"全身腫脹" "全身腫脹"
* TWCMClinicalFinding#"胸脹" "胸脹"
* TWCMClinicalFinding#"乳房脹" "乳房脹"
* TWCMClinicalFinding#"腹脹" "腹脹"
* TWCMClinicalFinding#"小腹脹" "小腹脹"
* TWCMClinicalFinding#"少腹脹" "少腹脹"
* TWCMClinicalFinding#"胃脹" "胃脹"
* TWCMClinicalFinding#"壓脹" "壓脹"
* TWCMClinicalFinding#"脹緩" "脹緩"
* TWCMClinicalFinding#"全身痛" "全身痛"
* TWCMClinicalFinding#"不定部位痛" "不定部位痛"
* TWCMClinicalFinding#"頭痛" "頭痛"
* TWCMClinicalFinding#"喉痛" "喉痛"
* TWCMClinicalFinding#"頸項痛" "頸項痛"
* TWCMClinicalFinding#"肩痛" "肩痛"
* TWCMClinicalFinding#"胸痛" "胸痛"
* TWCMClinicalFinding#"脅痛" "脅痛"
* TWCMClinicalFinding#"乳房痛" "乳房痛"
* TWCMClinicalFinding#"腹痛" "腹痛"
* TWCMClinicalFinding#"胃痛" "胃痛"
* TWCMClinicalFinding#"腰脊痛" "腰脊痛"
* TWCMClinicalFinding#"腰痛" "腰痛"
* TWCMClinicalFinding#"尾閭痛" "尾閭痛"
* TWCMClinicalFinding#"背痛" "背痛"
* TWCMClinicalFinding#"四肢痛" "四肢痛"
* TWCMClinicalFinding#"下肢痛" "下肢痛"
* TWCMClinicalFinding#"足跟痛" "足跟痛"
* TWCMClinicalFinding#"關節痛" "關節痛"
* TWCMClinicalFinding#"劇痛" "劇痛"
* TWCMClinicalFinding#"隱痛" "隱痛"
* TWCMClinicalFinding#"刺痛" "刺痛"
* TWCMClinicalFinding#"脹痛" "脹痛"
* TWCMClinicalFinding#"重痛" "重痛"
* TWCMClinicalFinding#"牽痛" "牽痛"
* TWCMClinicalFinding#"竄痛(走竄痛)" "竄痛(走竄痛)"
* TWCMClinicalFinding#"悶痛" "悶痛"
* TWCMClinicalFinding#"酸痛" "酸痛"
* TWCMClinicalFinding#"絞痛" "絞痛"
* TWCMClinicalFinding#"灼痛" "灼痛"
* TWCMClinicalFinding#"空痛" "空痛"
* TWCMClinicalFinding#"冷痛" "冷痛"
* TWCMClinicalFinding#"疼痛(非常不適無法忍耐、痛到哭)" "疼痛(非常不適無法忍耐、痛到哭)"
* TWCMClinicalFinding#"痛緩" "痛緩"
* TWCMClinicalFinding#"心悸（心悶）" "心悸（心悶）"
* TWCMClinicalFinding#"胃悶" "胃悶"
* TWCMClinicalFinding#"胸悶" "胸悶"
* TWCMClinicalFinding#"正常" "正常"
* TWCMClinicalFinding#"全身重" "全身重"
* TWCMClinicalFinding#"肩不舉" "肩不舉"
* TWCMClinicalFinding#"四肢沉重感" "四肢沉重感"
* TWCMClinicalFinding#"頸項僵" "頸項僵"
* TWCMClinicalFinding#"無力" "無力"
* TWCMClinicalFinding#"沒有力量" "沒有力量"
* TWCMClinicalFinding#"腰無力" "腰無力"
* TWCMClinicalFinding#"腰膝無力" "腰膝無力"
* TWCMClinicalFinding#"背僵" "背僵"
* TWCMClinicalFinding#"半身偏癱" "半身偏癱"
* TWCMClinicalFinding#"步態不穩" "步態不穩"
* TWCMClinicalFinding#"四肢沉重" "四肢沉重"
* TWCMClinicalFinding#"四肢拘急" "四肢拘急"
* TWCMClinicalFinding#"四肢強直" "四肢強直"
* TWCMClinicalFinding#"四肢無力" "四肢無力"
* TWCMClinicalFinding#"身體僵硬" "身體僵硬"
* TWCMClinicalFinding#"四肢僵硬" "四肢僵硬"
* TWCMClinicalFinding#"四肢抽掣(搐／顫抖)" "四肢抽掣(搐／顫抖)"
* TWCMClinicalFinding#"下肢沉重" "下肢沉重"
* TWCMClinicalFinding#"下肢無力" "下肢無力"
* TWCMClinicalFinding#"抽筋" "抽筋"
* TWCMClinicalFinding#"肉會亂跳" "肉會亂跳"
* TWCMClinicalFinding#"肌肉繃緊感" "肌肉繃緊感"
* TWCMClinicalFinding#"心悸" "心悸"
* TWCMClinicalFinding#"善驚(心驚)" "善驚(心驚)"
* TWCMClinicalFinding#"沒胃口(食量少、少食、不想食)" "沒胃口(食量少、少食、不想食)"
* TWCMClinicalFinding#"食欲旺盛" "食欲旺盛"
* TWCMClinicalFinding#"嘈雜" "嘈雜"
* TWCMClinicalFinding#"打嗝(腹脹打嗝)" "打嗝(腹脹打嗝)"
* TWCMClinicalFinding#"呃逆" "呃逆"
* TWCMClinicalFinding#"噁心" "噁心"
* TWCMClinicalFinding#"噁心感" "噁心感"
* TWCMClinicalFinding#"嘔吐(挾血、挾涎、挾胃液)" "嘔吐(挾血、挾涎、挾胃液)"
* TWCMClinicalFinding#"食後腹脹" "食後腹脹"
* TWCMClinicalFinding#"矢氣多（味道臭／不臭）" "矢氣多（味道臭／不臭）"
* TWCMClinicalFinding#"腹脹（部位）" "腹脹（部位）"
* TWCMClinicalFinding#"上吐下瀉" "上吐下瀉"
* TWCMClinicalFinding#"嘔" "嘔"
* TWCMClinicalFinding#"腰如繩束" "腰如繩束"
* TWCMClinicalFinding#"腰重" "腰重"

ValueSet: TWCMInquiryHeadFace
Id: twcm-inquiry-headface
Title: "頭面部(問)值集"
Description: "中醫門診單頭面部(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"頭重如裹" "頭重如裹"
* TWCMClinicalFinding#"頭脹" "頭脹"
* TWCMClinicalFinding#"頭重" "頭重"
* TWCMClinicalFinding#"太陽頭痛" "太陽頭痛"
* TWCMClinicalFinding#"少陽頭痛" "少陽頭痛"
* TWCMClinicalFinding#"陽明頭痛" "陽明頭痛"
* TWCMClinicalFinding#"太陰頭痛" "太陰頭痛"
* TWCMClinicalFinding#"少陰頭痛" "少陰頭痛"
* TWCMClinicalFinding#"厥陰頭痛" "厥陰頭痛"
* TWCMClinicalFinding#"頭項強痛" "頭項強痛"
* TWCMClinicalFinding#"項強" "項強"
* TWCMClinicalFinding#"面部疼痛" "面部疼痛"
* TWCMClinicalFinding#"面烘熱感" "面烘熱感"
* TWCMClinicalFinding#"易生痤瘡粉刺" "易生痤瘡粉刺"
* TWCMClinicalFinding#"健忘(意識健忘)" "健忘(意識健忘)"
* TWCMClinicalFinding#"頭暈" "頭暈"
* TWCMClinicalFinding#"頭旋" "頭旋"
* TWCMClinicalFinding#"頭皮麻木" "頭皮麻木"
* TWCMClinicalFinding#"頭痛（部位）" "頭痛（部位）"
* TWCMClinicalFinding#"偏頭痛" "偏頭痛"
* TWCMClinicalFinding#"頭冷" "頭冷"
* TWCMClinicalFinding#"頭熱" "頭熱"
* TWCMClinicalFinding#"頭傾" "頭傾"
* TWCMClinicalFinding#"腦鳴" "腦鳴"
* TWCMClinicalFinding#"頭皮癰腫" "頭皮癰腫"
* TWCMClinicalFinding#"痛緩" "痛緩"
* TWCMClinicalFinding#"麻" "麻"
* TWCMClinicalFinding#"頸項僵" "頸項僵"
* TWCMClinicalFinding#"頸項痛" "頸項痛"
* TWCMClinicalFinding#"頸粗" "頸粗"
* TWCMClinicalFinding#"頸後生癰" "頸後生癰"
* TWCMClinicalFinding#"頸間生瘡" "頸間生瘡"
* TWCMClinicalFinding#"甲狀腺痛" "甲狀腺痛"
* TWCMClinicalFinding#"吞下" "吞下"
* TWCMClinicalFinding#"吞不下" "吞不下"
* TWCMClinicalFinding#"噎" "噎"
* TWCMClinicalFinding#"流涎" "流涎"
* TWCMClinicalFinding#"口乾舌燥" "口乾舌燥"
* TWCMClinicalFinding#"味覺減弱" "味覺減弱"

ValueSet: TWCMInquiryEye
Id: twcm-inquiry-eye
Title: "目部(問)值集"
Description: "中醫門診單目部(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"目不澀" "目不澀"
* TWCMClinicalFinding#"目羞明(畏光)" "目羞明(畏光)"
* TWCMClinicalFinding#"目眩" "目眩"
* TWCMClinicalFinding#"目癢" "目癢"
* TWCMClinicalFinding#"易流淚" "易流淚"
* TWCMClinicalFinding#"眼屎多" "眼屎多"
* TWCMClinicalFinding#"目乾澀" "目乾澀"
* TWCMClinicalFinding#"眼癢" "眼癢"
* TWCMClinicalFinding#"目脹" "目脹"
* TWCMClinicalFinding#"目昏黑" "目昏黑"
* TWCMClinicalFinding#"視力模糊(視物模糊)" "視力模糊(視物模糊)"
* TWCMClinicalFinding#"視覺減弱" "視覺減弱"
* TWCMClinicalFinding#"目澀" "目澀"
* TWCMClinicalFinding#"乾" "乾"
* TWCMClinicalFinding#"潤" "潤"
* TWCMClinicalFinding#"不乾" "不乾"

ValueSet: TWCMInquiryEar
Id: twcm-inquiry-ear
Title: "耳朵(問)值集"
Description: "中醫門診單耳朵(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"耳痛" "耳痛"
* TWCMClinicalFinding#"重聽(重耳)" "重聽(重耳)"
* TWCMClinicalFinding#"耳癢" "耳癢"
* TWCMClinicalFinding#"耳塞脹" "耳塞脹"
* TWCMClinicalFinding#"耳鳴（轟聲如潮水聲／細弱如蟬聲）" "耳鳴（轟聲如潮水聲／細弱如蟬聲）"
* TWCMClinicalFinding#"耳聾" "耳聾"
* TWCMClinicalFinding#"耳衄(耳內出血)" "耳衄(耳內出血)"
* TWCMClinicalFinding#"耳內長肉" "耳內長肉"
* TWCMClinicalFinding#"耳內流膿" "耳內流膿"
* TWCMClinicalFinding#"痛緩" "痛緩"
* TWCMClinicalFinding#"脹緩" "脹緩"
* TWCMClinicalFinding#"聽覺減弱" "聽覺減弱"

ValueSet: TWCMInquiryNoseThroat
Id: twcm-inquiry-nosethroat
Title: "鼻咽部(問)值集"
Description: "中醫門診單鼻咽部(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"咽乾" "咽乾"
* TWCMClinicalFinding#"鼻塞" "鼻塞"
* TWCMClinicalFinding#"鼻乾" "鼻乾"
* TWCMClinicalFinding#"鼻衄" "鼻衄"
* TWCMClinicalFinding#"鼻涕(鼻流涕)" "鼻涕(鼻流涕)"
* TWCMClinicalFinding#"鼻水" "鼻水"
* TWCMClinicalFinding#"噴嚏" "噴嚏"
* TWCMClinicalFinding#"鼻頭冷" "鼻頭冷"
* TWCMClinicalFinding#"鼻孔乾燥" "鼻孔乾燥"
* TWCMClinicalFinding#"易流鼻血" "易流鼻血"
* TWCMClinicalFinding#"鼻臭" "鼻臭"
* TWCMClinicalFinding#"鼻痛" "鼻痛"
* TWCMClinicalFinding#"鼻腫" "鼻腫"
* TWCMClinicalFinding#"鼻痠" "鼻痠"
* TWCMClinicalFinding#"鼻癢" "鼻癢"
* TWCMClinicalFinding#"紅鼻子" "紅鼻子"
* TWCMClinicalFinding#"失嗅" "失嗅"
* TWCMClinicalFinding#"嗅覺減弱" "嗅覺減弱"
* TWCMClinicalFinding#"咽喉乾燥" "咽喉乾燥"
* TWCMClinicalFinding#"喉乾" "喉乾"
* TWCMClinicalFinding#"喉癢" "喉癢"
* TWCMClinicalFinding#"咽腫" "咽腫"
* TWCMClinicalFinding#"咽喉痛" "咽喉痛"
* TWCMClinicalFinding#"咽喉白腐" "咽喉白腐"
* TWCMClinicalFinding#"喉中梗阻" "喉中梗阻"
* TWCMClinicalFinding#"懸雍下垂" "懸雍下垂"
* TWCMClinicalFinding#"有痰哽感" "有痰哽感"
* TWCMClinicalFinding#"顏色(白、黃)" "顏色(白、黃)"
* TWCMClinicalFinding#"質(濃、濁、清)" "質(濃、濁、清)"
* TWCMClinicalFinding#"內容物(血)" "內容物(血)"
* TWCMClinicalFinding#"乾" "乾"
* TWCMClinicalFinding#"不乾" "不乾"

ValueSet: TWCMInquiryDietTaste
Id: twcm-inquiry-diettaste
Title: "飲食／口味(問)值集"
Description: "中醫門診單飲食／口味(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"咽乾" "咽乾"
* TWCMClinicalFinding#"口乾" "口乾"
* TWCMClinicalFinding#"口渴" "口渴"
* TWCMClinicalFinding#"口渴欲飲" "口渴欲飲"
* TWCMClinicalFinding#"渴不欲飲" "渴不欲飲"
* TWCMClinicalFinding#"飢不欲食" "飢不欲食"
* TWCMClinicalFinding#"消谷善飢" "消谷善飢"
* TWCMClinicalFinding#"納呆(納差、納少)" "納呆(納差、納少)"
* TWCMClinicalFinding#"厭食" "厭食"
* TWCMClinicalFinding#"口淡" "口淡"
* TWCMClinicalFinding#"口苦" "口苦"
* TWCMClinicalFinding#"口黏膩" "口黏膩"
* TWCMClinicalFinding#"口酸" "口酸"
* TWCMClinicalFinding#"口甜" "口甜"
* TWCMClinicalFinding#"口鹹" "口鹹"
* TWCMClinicalFinding#"口辛(口辣)" "口辛(口辣)"
* TWCMClinicalFinding#"口澀" "口澀"
* TWCMClinicalFinding#"口麻" "口麻"
* TWCMClinicalFinding#"口水多" "口水多"
* TWCMClinicalFinding#"口破" "口破"
* TWCMClinicalFinding#"舌頭破" "舌頭破"
* TWCMClinicalFinding#"口角流涎" "口角流涎"
* TWCMClinicalFinding#"喜(好、嗜)／惡(憎)冷飲" "喜(好、嗜)／惡(憎)冷飲"
* TWCMClinicalFinding#"溫飲" "溫飲"
* TWCMClinicalFinding#"熱飲" "熱飲"
* TWCMClinicalFinding#"但飲不多" "但飲不多"
* TWCMClinicalFinding#"但欲漱水不欲嚥" "但欲漱水不欲嚥"
* TWCMClinicalFinding#"渴不欲飲（渴不欲飲）" "渴不欲飲（渴不欲飲）"
* TWCMClinicalFinding#"渴而少飲（渴而少飲）" "渴而少飲（渴而少飲）"
* TWCMClinicalFinding#"食欲低落（食欲低落）" "食欲低落（食欲低落）"
* TWCMClinicalFinding#"苦味" "苦味"
* TWCMClinicalFinding#"鹹味" "鹹味"
* TWCMClinicalFinding#"酸味" "酸味"
* TWCMClinicalFinding#"腥味" "腥味"
* TWCMClinicalFinding#"甜味" "甜味"
* TWCMClinicalFinding#"澀味" "澀味"
* TWCMClinicalFinding#"淡味" "淡味"
* TWCMClinicalFinding#"喜食異物" "喜食異物"

ValueSet: TWCMInquirySleep
Id: twcm-inquiry-sleep
Title: "睡眠(問)值集"
Description: "中醫門診單睡眠(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"鼻鼾" "鼻鼾"
* TWCMClinicalFinding#"多夢" "多夢"
* TWCMClinicalFinding#"夢遊" "夢遊"
* TWCMClinicalFinding#"睡得安穩" "睡得安穩"
* TWCMClinicalFinding#"眠淺" "眠淺"
* TWCMClinicalFinding#"睡一半醒後不易入睡" "睡一半醒後不易入睡"
* TWCMClinicalFinding#"腳抽筋" "腳抽筋"
* TWCMClinicalFinding#"睡眠呼吸中止" "睡眠呼吸中止"
* TWCMClinicalFinding#"失眠" "失眠"
* TWCMClinicalFinding#"不寐(難眠)" "不寐(難眠)"
* TWCMClinicalFinding#"難入眠" "難入眠"
* TWCMClinicalFinding#"難入睡" "難入睡"
* TWCMClinicalFinding#"夢多(多夢)" "夢多(多夢)"
* TWCMClinicalFinding#"易睡醒" "易睡醒"
* TWCMClinicalFinding#"易醒" "易醒"
* TWCMClinicalFinding#"鼾聲" "鼾聲"

ValueSet: TWCMInquiryUrine
Id: twcm-inquiry-urine
Title: "小便(問)值集"
Description: "中醫門診單小便(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"小便黃赤(溺赤)" "小便黃赤(溺赤)"
* TWCMClinicalFinding#"餘瀝不盡" "餘瀝不盡"
* TWCMClinicalFinding#"小便頻數" "小便頻數"
* TWCMClinicalFinding#"小便澀痛" "小便澀痛"
* TWCMClinicalFinding#"赤" "赤"
* TWCMClinicalFinding#"色紅（小便色紅）" "色紅（小便色紅）"
* TWCMClinicalFinding#"紅赤(如濃茶)" "紅赤(如濃茶)"
* TWCMClinicalFinding#"黃赤(色棕)" "黃赤(色棕)"
* TWCMClinicalFinding#"色棕（小便色棕）" "色棕（小便色棕）"
* TWCMClinicalFinding#"色黃（小便色黃）" "色黃（小便色黃）"
* TWCMClinicalFinding#"多" "多"
* TWCMClinicalFinding#"少" "少"
* TWCMClinicalFinding#"無" "無"
* TWCMClinicalFinding#"泡沫" "泡沫"
* TWCMClinicalFinding#"濁(混濁)" "濁(混濁)"
* TWCMClinicalFinding#"色清(清長／小便量多)" "色清(清長／小便量多)"
* TWCMClinicalFinding#"味道" "味道"
* TWCMClinicalFinding#"正常" "正常"
* TWCMClinicalFinding#"脹滿(下腹／腹部)" "脹滿(下腹／腹部)"
* TWCMClinicalFinding#"失禁(小便失禁)" "失禁(小便失禁)"
* TWCMClinicalFinding#"遺尿" "遺尿"
* TWCMClinicalFinding#"漏出" "漏出"
* TWCMClinicalFinding#"頻尿" "頻尿"
* TWCMClinicalFinding#"急尿" "急尿"
* TWCMClinicalFinding#"小便急迫" "小便急迫"
* TWCMClinicalFinding#"小便不暢(不流利／不利／不通)" "小便不暢(不流利／不利／不通)"
* TWCMClinicalFinding#"排尿困難" "排尿困難"
* TWCMClinicalFinding#"點滴難下" "點滴難下"
* TWCMClinicalFinding#"排不出來" "排不出來"
* TWCMClinicalFinding#"尿後有餘瀝(小便不盡)" "尿後有餘瀝(小便不盡)"
* TWCMClinicalFinding#"無法小便" "無法小便"
* TWCMClinicalFinding#"無尿出" "無尿出"
* TWCMClinicalFinding#"尿血(小便挾血)" "尿血(小便挾血)"
* TWCMClinicalFinding#"小便挾精(小便挾精)" "小便挾精(小便挾精)"
* TWCMClinicalFinding#"挾乳糜（小便挾乳糜）" "挾乳糜（小便挾乳糜）"
* TWCMClinicalFinding#"小便渾濁(小便挾膿)" "小便渾濁(小便挾膿)"
* TWCMClinicalFinding#"澀痛" "澀痛"
* TWCMClinicalFinding#"小便疼痛" "小便疼痛"
* TWCMClinicalFinding#"灼熱" "灼熱"
* TWCMClinicalFinding#"尿道灼熱" "尿道灼熱"
* TWCMClinicalFinding#"小便灼熱" "小便灼熱"
* TWCMClinicalFinding#"夜尿" "夜尿"
* TWCMClinicalFinding#"非常不適無法忍耐" "非常不適無法忍耐"
* TWCMClinicalFinding#"痛到哭" "痛到哭"
* TWCMClinicalFinding#"痛緩" "痛緩"
* TWCMClinicalFinding#"脹緩" "脹緩"
* TWCMClinicalFinding#"白天次數／夜起次數(夜時次多/夜時小便次多)" "白天次數／夜起次數(夜時次多/夜時小便次多)"
* TWCMClinicalFinding#"小便次多" "小便次多"
* TWCMClinicalFinding#"小便次少" "小便次少"
* TWCMClinicalFinding#"量多（小便量多）" "量多（小便量多）"
* TWCMClinicalFinding#"量少（小便量少）" "量少（小便量少）"
* TWCMClinicalFinding#"痛" "痛"
* TWCMClinicalFinding#"寒熱" "寒熱"
* TWCMClinicalFinding#"腫脹" "腫脹"
* TWCMClinicalFinding#"壓脹" "壓脹"

ValueSet: TWCMInquiryStool
Id: twcm-inquiry-stool
Title: "大便(問)值集"
Description: "中醫門診單大便(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"溏結不調" "溏結不調"
* TWCMClinicalFinding#"里急後重" "里急後重"
* TWCMClinicalFinding#"完穀不化" "完穀不化"
* TWCMClinicalFinding#"五更泄瀉" "五更泄瀉"
* TWCMClinicalFinding#"肛門灼熱" "肛門灼熱"
* TWCMClinicalFinding#"硬硬的" "硬硬的"
* TWCMClinicalFinding#"散散的不成形" "散散的不成形"
* TWCMClinicalFinding#"成型(軟軟稀稀)" "成型(軟軟稀稀)"
* TWCMClinicalFinding#"水瀉" "水瀉"
* TWCMClinicalFinding#"腹瀉(大便泄瀉)" "腹瀉(大便泄瀉)"
* TWCMClinicalFinding#"大便溏" "大便溏"
* TWCMClinicalFinding#"大便黏滯" "大便黏滯"
* TWCMClinicalFinding#"大便秘結" "大便秘結"
* TWCMClinicalFinding#"大便艱難(大便不暢、不通、不利)" "大便艱難(大便不暢、不通、不利)"
* TWCMClinicalFinding#"排不出來" "排不出來"
* TWCMClinicalFinding#"急迫且里急後重" "急迫且里急後重"
* TWCMClinicalFinding#"大便墜重" "大便墜重"
* TWCMClinicalFinding#"大便失禁(大便失禁)" "大便失禁(大便失禁)"
* TWCMClinicalFinding#"大便下血(大便挾血)" "大便下血(大便挾血)"
* TWCMClinicalFinding#"大便膿血(大便挾膿。大便挾血)" "大便膿血(大便挾膿。大便挾血)"
* TWCMClinicalFinding#"排氣" "排氣"
* TWCMClinicalFinding#"痛緩" "痛緩"
* TWCMClinicalFinding#"一天次數" "一天次數"
* TWCMClinicalFinding#"好幾天一次" "好幾天一次"
* TWCMClinicalFinding#"次多" "次多"
* TWCMClinicalFinding#"次少" "次少"
* TWCMClinicalFinding#"味臭（大便味臭）" "味臭（大便味臭）"
* TWCMClinicalFinding#"黏" "黏"
* TWCMClinicalFinding#"初稀後濃" "初稀後濃"
* TWCMClinicalFinding#"軟" "軟"
* TWCMClinicalFinding#"初硬後稀" "初硬後稀"
* TWCMClinicalFinding#"稀" "稀"
* TWCMClinicalFinding#"初濃後稀" "初濃後稀"
* TWCMClinicalFinding#"硬" "硬"
* TWCMClinicalFinding#"濃" "濃"
* TWCMClinicalFinding#"糙" "糙"
* TWCMClinicalFinding#"膩" "膩"
* TWCMClinicalFinding#"非常不適無法忍耐" "非常不適無法忍耐"
* TWCMClinicalFinding#"痛到哭" "痛到哭"
* TWCMClinicalFinding#"脹緩" "脹緩"

ValueSet: TWCMInquiryMental
Id: twcm-inquiry-mental
Title: "精神／意識／行為／情緒／性格(問)值集"
Description: "中醫門診單精神／意識／行為／情緒／性格(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"乏力" "乏力"
* TWCMClinicalFinding#"煩熱" "煩熱"
* TWCMClinicalFinding#"煩躁" "煩躁"
* TWCMClinicalFinding#"疲乏（神疲／情緒神疲）" "疲乏（神疲／情緒神疲）"
* TWCMClinicalFinding#"提不起勁" "提不起勁"
* TWCMClinicalFinding#"幻聽" "幻聽"
* TWCMClinicalFinding#"幻視" "幻視"
* TWCMClinicalFinding#"幻覺" "幻覺"
* TWCMClinicalFinding#"善喜" "善喜"
* TWCMClinicalFinding#"善怒(憤怒)" "善怒(憤怒)"
* TWCMClinicalFinding#"易怒" "易怒"
* TWCMClinicalFinding#"急躁易怒" "急躁易怒"
* TWCMClinicalFinding#"善恐(恐懼)" "善恐(恐懼)"
* TWCMClinicalFinding#"善悲(悲傷)" "善悲(悲傷)"
* TWCMClinicalFinding#"善憂思(憂鬱／情緒憂鬱)" "善憂思(憂鬱／情緒憂鬱)"
* TWCMClinicalFinding#"抑鬱寡歡" "抑鬱寡歡"
* TWCMClinicalFinding#"懊惱" "懊惱"
* TWCMClinicalFinding#"心中懊憹" "心中懊憹"
* TWCMClinicalFinding#"心煩" "心煩"
* TWCMClinicalFinding#"易緊張煩躁(情緒煩躁)" "易緊張煩躁(情緒煩躁)"
* TWCMClinicalFinding#"焦慮" "焦慮"
* TWCMClinicalFinding#"心慌(情緒心慌)" "心慌(情緒心慌)"
* TWCMClinicalFinding#"心驚(情緒心驚)" "心驚(情緒心驚)"
* TWCMClinicalFinding#"壓力大" "壓力大"
* TWCMClinicalFinding#"多疑" "多疑"

ValueSet: TWCMInquiryFemale
Id: twcm-inquiry-female
Title: "婦女相關(問)值集"
Description: "中醫門診單婦女相關(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"白帶" "白帶"
* TWCMClinicalFinding#"黃帶" "黃帶"
* TWCMClinicalFinding#"赤白帶下" "赤白帶下"
* TWCMClinicalFinding#"白帶色黃" "白帶色黃"
* TWCMClinicalFinding#"白帶色棕" "白帶色棕"
* TWCMClinicalFinding#"五色帶" "五色帶"
* TWCMClinicalFinding#"白帶色清" "白帶色清"
* TWCMClinicalFinding#"濁" "濁"
* TWCMClinicalFinding#"清" "清"
* TWCMClinicalFinding#"黏" "黏"
* TWCMClinicalFinding#"白帶質稀" "白帶質稀"
* TWCMClinicalFinding#"多(白帶量多)" "多(白帶量多)"
* TWCMClinicalFinding#"少" "少"
* TWCMClinicalFinding#"無" "無"
* TWCMClinicalFinding#"臭" "臭"

ValueSet: TWCMInquiryMale
Id: twcm-inquiry-male
Title: "男性相關(問)值集"
Description: "中醫門診單男性相關(問)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"精液清冷" "精液清冷"
* TWCMClinicalFinding#"血精" "血精"
* TWCMClinicalFinding#"不射精" "不射精"
* TWCMClinicalFinding#"陽痿" "陽痿"
* TWCMClinicalFinding#"早泄" "早泄"
* TWCMClinicalFinding#"遺精" "遺精"
* TWCMClinicalFinding#"不孕" "不孕"
* TWCMClinicalFinding#"陰舉不衰" "陰舉不衰"
* TWCMClinicalFinding#"陰縮" "陰縮"
* TWCMClinicalFinding#"莖中痛癢" "莖中痛癢"
* TWCMClinicalFinding#"睪丸脹痛" "睪丸脹痛"
* TWCMClinicalFinding#"陰囊瘙癢" "陰囊瘙癢"
* TWCMClinicalFinding#"不舉" "不舉"

ValueSet: TWCMPalpationPressing
Id: twcm-palpation-pressing
Title: "按診(切)值集"
Description: "中醫門診單按診(切)之臨床表現詞彙值集，收錄自TWCMClinicalFinding代碼系統。"
* ^experimental = false
* TWCMClinicalFinding#"皮膚" "皮膚"
* TWCMClinicalFinding#"手足" "手足"
* TWCMClinicalFinding#"胸脅" "胸脅"
* TWCMClinicalFinding#"腹" "腹"
* TWCMClinicalFinding#"俞穴" "俞穴"
* TWCMClinicalFinding#"觸" "觸"
* TWCMClinicalFinding#"摸" "摸"
* TWCMClinicalFinding#"按" "按"
